Add pipupgrade command to update&upgrade all pip packages

diff --git a/zsh_aliases b/zsh_aliases
--- a/zsh_aliases
+++ b/zsh_aliases
@@ -155,3 +155,23 @@ function activate() {
         source ./$1/bin/activate
     fi
 }
+
+# Update pip and all its packages
+function pipupdate() {
+    which pip3 2>&1 > /dev/null
+    if [ $? = 0 ]; then  # if pip exists
+        echo "$prompt Updating pip3 itself. May ask for root password."
+        sudo -H pip3 install --upgrade pip
+        if [[ -z $(pip3 freeze --local) ]]; then
+            echo "$prompt No pip packages installed so far."
+        else
+            echo "$prompt Updating all pip3 packages."
+            pip3 freeze --local \
+                | grep -v '^\-e' \
+                | cut -d = -f 1  \
+                | xargs -n1 sudo -H pip3 install --upgrade
+        fi
+    else
+        echo "$prompt Missing pip3, skipping."
+    fi
+}
